/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(AperiodicSpectrumMatched.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(51e17ac396648b5ca82622697e9946d7)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/jammingSource/AperiodicSpectrumMatched.h>
// pydoc.h is automatically generated in the build directory
#include <AperiodicSpectrumMatched_pydoc.h>

void bind_AperiodicSpectrumMatched(py::module& m)
{

    using AperiodicSpectrumMatched    = ::gr::jammingSource::AperiodicSpectrumMatched;


    py::class_<AperiodicSpectrumMatched, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<AperiodicSpectrumMatched>>(m, "AperiodicSpectrumMatched", D(AperiodicSpectrumMatched))

        .def(py::init(&AperiodicSpectrumMatched::make),
           py::arg("samp_rate"),
           py::arg("chipRate"),
           D(AperiodicSpectrumMatched,make)
        )
        




        
        .def("sampling_freq",&AperiodicSpectrumMatched::sampling_freq,       
            D(AperiodicSpectrumMatched,sampling_freq)
        )


        
        .def("chip_rate",&AperiodicSpectrumMatched::chip_rate,       
            D(AperiodicSpectrumMatched,chip_rate)
        )


        
        .def("set_sampling_freq",&AperiodicSpectrumMatched::set_sampling_freq,       
            py::arg("sampling_freq"),
            D(AperiodicSpectrumMatched,set_sampling_freq)
        )


        
        .def("set_chip_rate",&AperiodicSpectrumMatched::set_chip_rate,       
            py::arg("chip_rate"),
            D(AperiodicSpectrumMatched,set_chip_rate)
        )

        ;




}








